### ISSUE TITLE
dht._findProvidersSingle returns duplicate providers

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-kad-dht#124]
I frequently see the reponse `msg.providerPeers` contain the same peer many times. I just saw one that had 227 providers where only 5 were unique by `peerId`. weird! :alien: 

I've never seen any duplicates in `msg.closerPeers`

**Comment by kumavis** [comment]
maybe something related to caching? seems to happen more often when i ask the network for the same key a few times

**Comment by jacobheun** [comment]
It looks like this is likely an issue with the provider cache map, https://github.com/libp2p/js-libp2p-kad-dht/blob/v0.15.0/src/providers.js#L241.

It's adding the `PeerId` to the map, which won't deduplicate because those stored PeerId's are likely different instances. That's going to need to be changed to do better validation to ensure uniqueness.

**Comment by dirkmc** [comment]
There are some fixes to that and other issues with Provider caching here:
https://github.com/libp2p/js-libp2p-kad-dht/pull/82/files#diff-1b3f398ccd8edf16e368e71d0fe5eda9R190
