### ISSUE TITLE
Compatibility issue with go-libp2p-kad-dht

### ISSUE THREAD

**Issue by iNDicat0r** [libp2p/js-libp2p-kad-dht#216]
Hi

I am trying to discover nodes using the `.contentRouting.findProviders` in `js-libp2p-kad-dht`. There are  other peers written in golang, and the `advertise functionlity` uses `go-libp2p-kad-dht`.

Golang peer:
```
...
discovery.Advertise(ctx, n.RoutingDiscovery, "FINDMEHERE")
```

Consider the following in nodejs:

```
const bytes = new TextEncoder("utf8").encode("FINDMEHERE");
const hash = await multihashing(bytes, "sha2-256");
const cid = new CID(1, "raw", hash);
....
const providers = await all(node.contentRouting.findProviders(cid));
```

Nodejs can't find any provider, i get the `not found` exception. Are those libs compatible the way they `advertise` and `findPeer` ?

**Comment by vasco-santos** [comment]
Thanks for reaching out @iNDicat0r 
They are compatible and interoperable, but you might be hitting connectivity issues that make your JS node not able to bootstrap its network in order to find the go node. The JS DHT does not provide the same reliability as the GO DHT, we are looking into upgrading the JS DHT with the learnings from the updates that got in the GO DHT last year.
Meanwhile, I highly recommend you use delegate routing: https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#setup-with-content-and-peer-routing
There several public delegate routers available: https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/src/runtime/config-nodejs.js#L14-L17

**Comment by iNDicat0r** [comment]
Thanks @vasco-santos 

I will take a look at it. Does IPFS uses delegate routing? Isn't it too centralized?

**Comment by vasco-santos** [comment]
`js-ipfs` relies on the delegates yes. You need to rely on the availability of a given set of delegates.

These delegates are `go-libp2p` nodes acting as DHT servers, so basically you are delegating DHT queries to them. They will do the regular DHT query and return back the results.
