### ISSUE TITLE
DHT and circuit relay

### ISSUE THREAD

**Issue by RangerMauve** [libp2p/js-libp2p-kad-dht#22]
Hello,
I was wondering whether the DHT logic for connecting to peers will be making use of circuit relay once that becomes available in order to connect to peers using different transports (e.g. browsers)

**Comment by lgierth** [comment]
Yes, but that's not a concern of the DHT, and the underlying connections are completely transparent to the DHT.

**Comment by RangerMauve** [comment]
So a node will be able to traverse the DHT and make connections to intermediate nodes regardless of whether they have matching transports?
So once, circuit-relay gets added to js-ipfs we'll have browser participating in the DHT without issues?

**Comment by dryajov** [comment]
Yes, that is (in part) exactly the concern of circuit-relay to connect nodes that otherwise don't share the same protocols. So, as long as browsers can connect to the rest of the network, which circuit-relay should help with, the DHT should work transparently in the browser. Although, circuit-relay is not the only way of "bridging" browser nodes, there are other transports that currently allow that, albeit in a somewhat centralized way, i.e. `websocket-star` and `webrtc-star`, which both require a rendevouz server.

**Comment by RangerMauve** [comment]
Thank you both very much for the clarification!
I wasn't sure whether modules utilizing the swarm needed to do anything special in order to support circuit-relay, this clears things up quite a bit!
